Feature/home screen
kzi-nastava/ma-project-event-planner-siit-2024-team-10 pull request #21
Opened 2024-11-21 14:36 UTC by marina-ivanovic

Changed designs of event/offering cards, added location and date attributes to the Event class.

2024-11-22 07:39 UTC, milicaradicc commented on EventPlanner/app/src/main/java/m3/eventplanner/fragments/TopEventsFragment.java
> +    private List<Event> getTopEvents() {
Add some error handling or empty state management. For example, if the list of events is empty, you can display a "No Events Available" message or some fallback UI

2024-11-22 07:42 UTC, milicaradicc requested changes

2024-11-22 07:42 UTC, milicaradicc commented on EventPlanner/app/src/main/java/m3/eventplanner/fragments/TopOfferingsFragment.java
> +        offeringList = getOfferingList();  // Ensure this method provides data
Add some error handling or empty state management

2024-11-22 07:44 UTC, milicaradicc commented on EventPlanner/app/src/main/java/m3/eventplanner/fragments/TopOfferingsFragment.java
> +        offeringList = getOfferingList();  // Ensure this method provides data
Design looks great,  implementing an empty state is necessary. Add error handling and loading states for a better user experience.

2024-11-22 07:44 UTC, milicaradicc commented
Design looks great, implementing an empty state is necessary. Add error handling and loading states for a better user experience.

2024-11-22 13:18 UTC, marina-ivanovic commented
Changes made:
- Made a display text for when the list of events/offerings is empty.
- Combined all of the xml and Java files for display of cards (allEvents/topEvents/allOfferings/topOfferings fragments and xml files) into one fragment and created the logic for displaying and hiding components depending on the tab the user clicked on.
- Changed the search bar from custom made one, to material design search bar
- Renamed the filter components, but the components themselves will be changed on another branch

- There is no longer need to separate the recycler view from the component it's getting used in, if you want to reuse the component, there is no need to make another xml, just make the recycler view for that list. The logic for putting the the cards in the recycler view is in the home fragment, and the adapters for events/offerings can be used for binding the data to the cards.

2024-11-23 10:17 UTC, milicaradicc approved these changes

2024-11-23 10:17 UTC, merged